### ISSUE TITLE
list object has no attribute strip, line 80 in cli.py

### ISSUE THREAD

**Issue by vmaffei** [ddomingof/PubMed2PDF#2]
Getting the above error when running --pmidsfile="/path/to/file.txt". The pmids are separated by lines in the file. Seems to be triggered by "line.strip().split().strip()" and fixed by deleting .strip() at the end. Not sure if this is a bug or a simple workaround for my incorrect usage lol. Thanks!

**Comment by ddomingof** [comment]
Should be fixed now with the PR
